apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appName }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.appName }}
spec:
  ports:
  - port: 5000
    protocol: TCP
    name: flask
  - port: 8001
    protocol: TCP
    name: prometheus 
  selector:
    app: {{ .Values.appName }}
    tier: frontend
  type: NodePort